on: 
  push:
    branches:
      - demo-godaddy
name: 🚀 Deploy website to GoDaddy demo site
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ftp.vflits.com
        username: sam.wpang.net@vflits.com
        password: ${{ secrets.ftp_password }}
